// pkg/ui/src/components/NoteButton/NoteButton.tsx
import React from "react";

import ArrowCircleLeft from "@assets/ArrowCircleLeft.svg";
import ArrowCircleRight from "@assets/ArrowCircleRight.svg";

// #region types
export interface NoteButtonProps
  extends React.HTMLAttributes<HTMLButtonElement> {
  type?: NoteButtonType;
  label?: NoteButtonLabel | Warehouse;
  shape?: NoteButtonShape;
  onClick?: () => void;
}

export enum NoteButtonShape {
  Square = "rounded-md",
  RoundedRight = "rounded-r-md",
}

export enum NoteButtonLabel {
  RemoveBooks = "Remove Books",
}

export enum NoteButtonType {
  In = "in",
  Out = "out",
}

export enum Warehouse {
  Scolastica = "scolastica",
  Nuovo = "nuovo",
  Varia = "varia",
}
// #endregion types

// #region color
const colorClassesLookup = {
  [NoteButtonType.In]: ["text-white", "bg-green-400", "hover:bg-green-500"],
  [NoteButtonType.Out]: ["text-white", "bg-red-400", "hover:bg-red-500"],
};

// #endregion color

// #region Component
/**
 * A note button component implementing styles from the mockup.
 * In: green, warehouse label, two side sharp and two side square
 * Out: red, warehouse label, two side sharp and two side square
 * Global out: red, remove books label, square
 * @param {Object} props
 * @param {NoteButtonType} props.type
 * @param {NoteButtonLabel | Warehouse} props.label
 * @param {NoteButtonShape} props.shape
 * @param {JSX.Element | JSX.Element[]} props.children
 */
const NoteButton: React.FC<NoteButtonProps> = ({
  children,
  type = NoteButtonType.In,
  label = Warehouse.Varia,
  shape = NoteButtonShape.Square,
  onClick = () => {},
  className: classes = "",
  ...props
}) => {
  // const shape =
  //   label === NoteButtonLabel.RemoveBooks ? "rounded-md" : "rounded-r-md";
  const text = ["text-md", "leading-5"];
  const shapeSpacing = ["px-4.25", "py-2.25"];
  const color = colorClassesLookup[type];

  const className = [shape, ...text, ...shapeSpacing, ...color].join(" ");

  return (
    <span className={[classes, "flex items-center"].join()}>
      <button onClick={onClick} {...props} className={className}>
        <ButtonContent {...{ children, type, label }} />
      </button>
    </span>
  );
};

// #endregion Component

/**
 * A text part of the button with the icon
 * @param {Object} props
 * @param {NoteButtonType} props.type
 * @param {NoteButtonLabel} props.label
 */
const ButtonContent: React.FC<
  Required<Pick<NoteButtonProps, "type" | "label">>
> = ({ type, label }) => {
  const iconSizeClasses = ["w-6", "h-6"];
  const iconSpacingClasses = ["mr-1.5", "-left-0.5"];
  const iconColorClass = "text-white";

  const WrapIcon: React.FC<Pick<NoteButtonProps, "children">> = ({
    children,
  }) => (
    <div
      className={[
        "relative",
        ...iconSizeClasses,
        ...iconSpacingClasses,
        iconColorClass,
      ].join(" ")}
    >
      {children}
    </div>
  );

  return (
    <span className="flex items-center">
      <WrapIcon>
        {type === NoteButtonType.In ? (
          <ArrowCircleRight />
        ) : (
          <ArrowCircleLeft />
        )}
      </WrapIcon>
      {label}
    </span>
  );
};

export default NoteButton;

// pkg/ui/src/NoteButton/NoteButton.svelte
<script lang="ts">
	import { ArrowCircleRight, ArrowCircleLeft } from '@librocco/svg';

	import { NoteButtonLabel, NoteButtonType, Warehouse } from './enums';

	import {
		text,
		shapeSpacing,
		iconSizeClasses,
		iconSpacingClasses,
		iconColorClass,
		colorClassesLookup,
		borderClassesLookup
	} from './styles';

	export let type: NoteButtonType = NoteButtonType.In;
	export let label: NoteButtonLabel | Warehouse = Warehouse.Nuovo;
	export let classes: string = '';

	const arrowIconLookup = {
		[NoteButtonType.In]: ArrowCircleRight,
		[NoteButtonType.Out]: ArrowCircleLeft
	};
	const Icon = arrowIconLookup[type];

	const color = colorClassesLookup[type];
	const border = borderClassesLookup[label];
	const buttonClasses = [
		classes,
		'flex',
		'items-center',
		border,
		...text,
		...shapeSpacing,
		...color
	].join(' ');
	const buttonContentClasses = [
		'flex',
		'items-center',
		...iconSizeClasses,
		...iconSpacingClasses,
		iconColorClass
	].join(' ');
</script>

<span class={border}>
	<button class={buttonClasses}>
		<div class={buttonContentClasses}>
			<svelte:component this={Icon} />
		</div>
		{label}
	</button>
</span>
