// pkg/couchdb/ui/src/Button/Button.svelte
<script lang="ts">
	import type { SvelteComponentDev } from 'svelte/internal';

	import { ButtonColor, ButtonShape, ButtonSize, IconPosition } from './enums';
	import {
		shapeRadiusLookup,
		textSizeLookup,
		shapeSpacingLookup,
		colorClassesLookup,
		iconSizeLookup,
		iconSpacingLookup,
		iconColorLookup
	} from './styles';

	let className = '';
	export { className as class };
	/**
	 * Size of the button component, applies the following styles with respect to size:
	 * ```yaml
	 * text-size:
	 * 	xs:   text-xs   leading-4
	 * 	sm:   text-sm   leading-4
	 * 	base: text-sm   leading-5
	 * 	lg:   text-base leading-6
	 * 	xl:   text-base leading-6
	 *
	 * spacing: # with respect to shape
	 * 	square:
	 * 		xs:   px-[11px] py-1.75
	 * 		sm:   px-3.25   py-2.25
	 * 		base: px-4.25   py-2.25
	 * 		lg:   px-4.25   py-2.25
	 * 		xl:   px-6.25   py-3.25
	 *
	 * 	rounded:
	 * 		xs:   px-3.25   py-1.75
	 * 		sm:   px-[15px] py-2.25
	 * 		base: px-4.25   py-2.25
	 * 		lg:   px-[21px] py-2.25
	 * 		xl:   px-6.25   py-3.25
	 *
	 * 	circular:
	 * 		xs:   p-[5px]
	 * 		sm:   p-1.75
	 * 		base: p-2.25
	 * 		lg:   p-2.25
	 * 		xl:   p-3.25
	 *
	 * icon-size:
	 * 	xs:   w-4 h-4
	 * 	sm:   w-4 h-4
	 * 	base: w-5 h-5
	 * 	lg:   w-5 h-5
	 * 	xl:   w-5 h-5
	 * ```
	 */
	export let size: ButtonSize = ButtonSize.Base;
	/**
	 * Rounding of the edges (`border-radius`) of a button, applies the following classes with respect to shape:
	 * ```yaml
	 * rounded:  rounded-full
	 *
	 * square: # with respect to size
	 * 	xs:   rounded
	 * 	sm:   rounded-md
	 * 	base: rounded-md
	 * 	lg:   rounded-md
	 * 	xl:   rounded-md
	 *
	 * rounded: # with respect to size
	 * 	xs:   rounded-[15px]
	 * 	sm:   rounded-[17px]
	 * 	base: rounded-[19px]
	 * 	lg:   rounded-[21px]
	 * 	xl:   rounded-[25px]
	 * ```
	 */
	export let shape: ButtonShape = ButtonShape.Square;
	/**
	 * Applies canned colorings for a button:
	 * ```yaml
	 * primary:
	 * 	text-white bg-indigo-600 hover:bg-indigo-700
	 * secondary:
	 * 	text-indigo-700 bg-indigo-100 hover:bg-indigo-200
	 * white:
	 * 	text-gray-700 bg-white border border-gray-300 hover:bg-gray-50
	 * ```
	 */
	export let color: ButtonColor = ButtonColor.Primary;
	/**
	 * Optional icon SVG as svelte component
	 */
	export let Icon: typeof SvelteComponentDev | null = null;
	export let iconPosition: IconPosition = IconPosition.Start;
	/**
	 * A custom html tag we want to render the element as (defaults to "button")
	 */
	export let as: string = 'button';

	$: shapeClass = shape === ButtonShape.Circular ? 'rounded-full' : shapeRadiusLookup[shape][size];
	$: textClasses = textSizeLookup[size];
	$: spacingClasses = shapeSpacingLookup[shape][size];
	$: sizeClasses = [textClasses, spacingClasses].join(' ');
	$: colorClasses = colorClassesLookup[color];
	const focusClasses =
		'focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-white';
	$: containerClasses = [sizeClasses, shapeClass, colorClasses, focusClasses, className].join(' ');

	$: showIcon = Icon && shape !== ButtonShape.Circular;
	$: iconSizeClasses = iconSizeLookup[size];
	$: iconSpacingClasses = iconSpacingLookup[iconPosition][size];
	$: iconColorClass = iconColorLookup[color];
	$: iconClasses = ['block', iconSizeClasses, iconSpacingClasses, iconColorClass].join(' ');
</script>

<svelte:element this={as} class={containerClasses} on:click>
	<span class="flex items-center">
		{#if showIcon && iconPosition === IconPosition.Start}
			<span class={iconClasses}><svelte:component this={Icon} /></span>
		{/if}

		<slot />

		{#if showIcon && iconPosition === IconPosition.End}
			<span class={iconClasses}><svelte:component this={Icon} /></span>
		{/if}
	</span>
</svelte:element>

// pkg/ui-react/src/components/Button/Button.tsx
import React from "react";

import { SVGComponent } from "@librocco/shared";

import PlusIcon from "@assets/Plus.svg";

// #region types
export enum ButtonShape {
  Square = "square",
  Rounded = "rounded",
  Circular = "circular",
}

export enum ButtonColor {
  Primary = "primary",
  White = "white",
  Secondary = "secondary",
}

export enum ButtonSize {
  XS = "xs",
  SM = "sm",
  Base = "md",
  LG = "lg",
  XL = "xl",
}

export enum IconPosition {
  Start = "left",
  End = "right",
}

export interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement> {
  size?: ButtonSize;
  shape?: ButtonShape;
  color?: ButtonColor;
  Icon?: SVGComponent;
  iconPosition?: IconPosition;
  as?: keyof JSX.IntrinsicElements;
}
// #endregion types

// #region Component

// #region Component
/**
 * A base button component implementing styles from the mockup.
 * @param {Object} props
 * @param {ButtonSize} props.size
 * @param {ButtonShape} props.shape
 * @param {ButtonColor} props.color
 * @param {SVGComponent} props.Icon
 * @param {IconPosition} props.iconPosition
 * @param {string} props.as
 * @param {string} props.classes
 * @param {JSX.Element | JSX.Element[]} props.children
 */
const Button: React.FC<ButtonProps> = ({
  size = ButtonSize.Base,
  shape = ButtonShape.Square,
  color = ButtonColor.Primary,
  Icon,
  iconPosition = IconPosition.Start,
  as = "button",
  className: classes = "",
  children,
  ...props
}) => {
  const sizeClasses = getSizeClasses(shape, size);

  const shapeClass = getRadiusClass(shape, size);

  const colorClasses = colorClassesLookup[color];

  const className = [...sizeClasses, shapeClass, ...colorClasses, classes].join(
    " "
  );

  const content =
    shape === ButtonShape.Circular ? (
      <CircularContent {...{ children, size }} />
    ) : (
      <ButtonContent {...{ size, color, children, Icon, iconPosition }} />
    );

  return React.createElement(as, { ...props, className }, content);
};
// #endregion Component

// #region borderRadius
const getRadiusClass = (shape: ButtonShape, size: ButtonSize): string =>
  shape === ButtonShape.Circular
    ? "rounded-full"
    : shapeRadiusLookup[shape][size];

const shapeRadiusLookup = {
  [ButtonShape.Square]: {
    [ButtonSize.XS]: "rounded",
    [ButtonSize.SM]: "rounded-md",
    [ButtonSize.Base]: "rounded-md",
    [ButtonSize.LG]: "rounded-md",
    [ButtonSize.XL]: "rounded-md",
  },
  [ButtonShape.Rounded]: {
    [ButtonSize.XS]: "rounded-[15px]",
    [ButtonSize.SM]: "rounded-[17px]",
    [ButtonSize.Base]: "rounded-[19px]",
    [ButtonSize.LG]: "rounded-[21px]",
    [ButtonSize.XL]: "rounded-[25px]",
  },
};
// #endregion borderRadius

// #region size
const getSizeClasses = (shape: ButtonShape, size: ButtonSize): string[] => {
  const textClasses = textSizeLookup[size];
  const spacingClasses = shapeSpacingLookup[shape][size];

  return [...textClasses, ...spacingClasses, ...focusClasses];
};

const textSizeLookup = {
  [ButtonSize.XS]: ["text-xs", "leading-4"],
  [ButtonSize.SM]: ["text-sm", "leading-4"],
  [ButtonSize.Base]: ["text-sm", "leading-5"],
  [ButtonSize.LG]: ["text-base", "leading-6"],
  [ButtonSize.XL]: ["text-base", "leading-6"],
};

const shapeSpacingLookup = {
  [ButtonShape.Square]: {
    [ButtonSize.XS]: ["px-[11px]", "py-1.75"],
    [ButtonSize.SM]: ["px-3.25", "py-2.25"],
    [ButtonSize.Base]: ["px-4.25", "py-2.25"],
    [ButtonSize.LG]: ["px-4.25", "py-2.25"],
    [ButtonSize.XL]: ["px-6.25", "py-3.25"],
  },
  [ButtonShape.Rounded]: {
    [ButtonSize.XS]: ["px-3.25", "py-1.75"],
    [ButtonSize.SM]: ["px-[15px]", "py-2.25"],
    [ButtonSize.Base]: ["px-4.25", "py-2.25"],
    [ButtonSize.LG]: ["px-[21px]", "py-2.25"],
    [ButtonSize.XL]: ["px-6.25", "py-3.25"],
  },
  [ButtonShape.Circular]: {
    [ButtonSize.XS]: ["p-[5px]"],
    [ButtonSize.SM]: ["p-1.75"],
    [ButtonSize.Base]: ["p-2.25"],
    [ButtonSize.LG]: ["p-2.25"],
    [ButtonSize.XL]: ["p-3.25"],
  },
};
// #endregion size

// #region color
const colorClassesLookup = {
  [ButtonColor.Primary]: ["text-white", "bg-indigo-600", "hover:bg-indigo-700"],
  [ButtonColor.Secondary]: [
    "text-indigo-700",
    "bg-indigo-100",
    "hover:bg-indigo-200",
  ],
  [ButtonColor.White]: [
    "text-gray-700",
    "bg-white",
    "border",
    "border-gray-300",
    "hover:bg-gray-50",
  ],
};

// Classes for focus pseudo-class are the same regardless of color prop
const focusClasses = [
  "focus:ring-2",
  "focus:ring-indigo-500",
  "focus:ring-offset-2",
  "focus:ring-offset-white",
];
// #endregion color

// #region buttonContent
/**
 * A component to be rendered as content in circular button.
 * This would normally be only the Icon SVG.
 * @param {Object} props
 * @param {JSX.Element | JSX.Element[]} props.children should be SVG Icon, if not provided falls back to `PlusIcon`
 * @param {ButtonSize} props.size
 */
const CircularContent: React.FC<Pick<ButtonProps, "children" | "size">> = ({
  children,
  size = ButtonSize.Base,
}) => (
  <div className={circularContentSizeLookup[size].join(" ")}>
    {children || <PlusIcon />}
  </div>
);

const circularContentSizeLookup = {
  [ButtonSize.XS]: ["w-4", "h-4"],
  [ButtonSize.SM]: ["w-4", "h-4"],
  [ButtonSize.Base]: ["w-4", "h-4"],
  [ButtonSize.LG]: ["w-5", "h-5"],
  [ButtonSize.XL]: ["w-5", "h-5"],
};

/**
 * A text part of the button with optional icon at the start or the end.
 * @param {Object} props
 * @param {JSX.Element | JSX.Element[]} props.children should be just the text
 * @param {ButtonSize} props.size
 * @param {SVGComponent} props.Icon
 * @param {IconPosition} props.iconPosition
 * @param {ButtonColor} props.color
 */
const ButtonContent: React.FC<
  Pick<ButtonProps, "children" | "Icon"> &
    Required<Pick<ButtonProps, "iconPosition" | "size" | "color">>
> = ({ children, size, Icon, iconPosition, color }) => {
  if (!Icon) {
    return <>{children}</>;
  }

  const iconSizeClasses = iconSizeLookup[size];
  const iconSpacingClasses = iconSpacingLookup[iconPosition][size];
  const iconColorClass = iconColorLookup[color];

  const WrapIcon: React.FC<Pick<ButtonProps, "children">> = ({ children }) => (
    <div
      className={[
        "relative",
        ...iconSizeClasses,
        ...iconSpacingClasses,
        iconColorClass,
      ].join(" ")}
    >
      {children}
    </div>
  );

  return (
    <span className="flex items-center">
      {iconPosition === IconPosition.Start && (
        <WrapIcon>
          <Icon />
        </WrapIcon>
      )}
      {children || null}
      {iconPosition === IconPosition.End && (
        <WrapIcon>
          <Icon />
        </WrapIcon>
      )}
    </span>
  );
};

const iconSizeLookup = {
  [ButtonSize.XS]: ["w-4", "h-4"],
  [ButtonSize.SM]: ["w-4", "h-4"],
  [ButtonSize.Base]: ["w-5", "h-5"],
  [ButtonSize.LG]: ["w-5", "h-5"],
  [ButtonSize.XL]: ["w-5", "h-5"],
};

const iconSpacingLookup = {
  [IconPosition.Start]: {
    // According to mockup, margin right here should be 8px
    // however, in order to not mess with the original padding of the button (container of this element)
    // we're offsetting to the left by 2px (hence the '-left-0.5'). This, however
    // leaves the margin in place (from original position), therefore, all margins are offset by 2px
    // 8px - 2px = 6px --> hence 'mr-1.5'
    [ButtonSize.XS]: ["mr-1.5", "-left-0.5"],
    [ButtonSize.SM]: ["mr-1.5", "-left-0.5"],
    [ButtonSize.Base]: ["mr-1.5", "-left-0.5"],
    [ButtonSize.LG]: ["mr-2.5", "-left-0.5"],
    [ButtonSize.XL]: ["mr-2.5", "-left-0.5"],
  },
  [IconPosition.End]: {
    [ButtonSize.XS]: ["ml-1.5", "left-0.5"],
    [ButtonSize.SM]: ["ml-1.5", "left-0.5"],
    [ButtonSize.Base]: ["ml-1.5", "left-0.5"],
    [ButtonSize.LG]: ["ml-2.5", "left-0.5"],
    [ButtonSize.XL]: ["ml-2.5", "left-0.5"],
  },
};

const iconColorLookup = {
  [ButtonColor.Primary]: "text-white",
  [ButtonColor.Secondary]: "text-indigo-500",
  [ButtonColor.White]: "text-gray-500",
};
// #endregion buttonContent

export default Button;
